### ISSUE TITLE
Issue with BNBCore/BNBLib and DimensionStages

### ISSUE THREAD

**Issue by kotovskii** [Darkhax-Minecraft/DimensionStages#4]
Hello. I have problem with DimensionStages and BNBGaming Core/Lib, Minecraft keeps crashing on generating a new world even after i fully removed modified configs and removed all scripts from modpack.
DimensionalControl-1.12.2-2.10.2
BNBGamingLib-1.12.2-2.17.0 (Tried stable 2.16.0)
BNBGamingCore-1.12.2-0.10.0
[latest.log](https://github.com/Darkhax-Minecraft/DimensionStages/files/2724798/latest.log)

**Comment by Darkhax** [comment]
The actual crash seems to be with BNB Lib. 

```
[20:09:34] [main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1771) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchMethodError: com.bloodnbonesgaming.lib.util.script.ScriptUtil.readScript(Ljava/io/File;Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;
	at com.bloodnbonesgaming.dimensionalcontrol.util.IOHelper.loadMainConfig(IOHelper.java:105) ~[IOHelper.class:?]
	at com.bloodnbonesgaming.dimensionalcontrol.client.event.ClientEventHandler.onActionPerformed(ClientEventHandler.java:88) ~[ClientEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1514_ClientEventHandler_onActionPerformed_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:438) ~[blk.class:?]
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416) ~[boi.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) ~[blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758) ~[bib.class:?]
	... 9 more
```
